name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # Checkout the repository

      - name: SSH into EC2 Server and Deploy
        uses: appleboy/ssh-action@master # Use the SSH action to connect to the EC2 instance
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 instance IP or hostname
          username: ${{ secrets.EC2_USERNAME }} # EC2 instance username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Private SSH key stored as a GitHub secret
          script: |
            sudo chown -R ${{ secrets.EC2_USERNAME }}:${{ secrets.EC2_USERNAME}} /var/www/Lydiapp # Change the owner of the project directory
            sudo find /var/www/Lydiapp -type d -exec chmod 755 {} \; # Set directory permissions
            sudo find /var/www/Lydiapp -type f -exec chmod 644 {} \; # Set file permissions
            sudo -s # Start a root shell to run the following commands
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - # Install Node.js and npm
            sudo apt-get install -y nodejs
            cd /var/www/Lydiapp # Change to the project directory
            git pull origin main # Pull the latest changes from the main branch
            composer install --no-interaction --prefer-dist --optimize-autoloader # Install PHP dependencies
            php artisan config:cache # Clear the config cache
            php artisan route:cache # Clear the route cache
            export PATH=$PATH:./node_modules/.bin # Add node_modules/.bin to the PATH
            chmod +x ./node_modules/.bin/vite # Make sure vite has execute permissions
            npm install && npm run build # Install Node.js dependencies and compile assets
