name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # Checkout the repository

      - name: SSH into EC2 Server and Deploy
        uses: appleboy/ssh-action@master # Use the SSH action to connect to the EC2 instance
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 instance IP or hostname
          username: ${{ secrets.EC2_USERNAME }} # EC2 instance username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Private SSH key stored as a GitHub secret
          script: |
            sudo -s # Start a root shell to run the following commands
            cd /var/www/Lydiapp # Change to the project directory
            git pull origin main # Pull the latest changes from the main branch
            sudo chown -R www-data:www-data storage bootstrap/cache # Set the correct ownership
            sudo chmod -R 775 storage bootstrap/cache # Set the correct permissions
            php artisan config:cache # Clear the config cache
            php artisan route:cache # Clear the route cache
            php artisan view:cache # Clear the view cache
            php artisan cache:clear # Clear the application cache
            php artisan migrate --force # Run the database migrations
